### ISSUE TITLE
Integration with bootstrap way of showing modals?

### ISSUE THREAD

**Issue by thehappycoder** [xue2han/react-dynamic-modal#2]
I tried to use react-dynamic-modal together with bootstrap way of showing modals, so that I have:
- the default effect when modal appears
- the modal-backdrop

I was successful, but it's kind of an ugly hack :)

What do you think about this?

```
ModalManager.open(<UserMembershipChangeModal onRequestClose={() => true}/>);
    $('.modal').modal('show');
```

```
<Modal
        overlayClassName="modal fade"
        className="modal-dialog"
        onRequestClose={() => $('.modal').modal('hide')}
        openTimeoutMS={150}
        closeTimeoutMS={150}
        style={{
          overlay: {
            backgroundColor: 'transparent',
          },

          content: {
            position: 'relative',
            top: 'initial',
            right: 'initial',
            bottom: 'initial',
            left: 'initial',
            overflow: 'initial',
            border: 'none',
            background: 'initial',
            padding: 0
          }
        }}
        >
```

**Comment by xue2han** [comment]
Well.React-dynamic-modal is not built for bootstrap,but for general usage.So if you want to make it like Bootstrap modal,you should modify the css and you shouldn't call `$('.modal').modal('hide')` or `$('.modal').modal('show')`,let Reac-dynamic-modal handle with it.
this is css from my demo for bootstrap:

``` css
.ReactModal__Overlay {
  -webkit-perspective: 600;
  perspective: 600;
  opacity: 0;
  overflow-x: hidden;
  overflow-y: auto;
  background-color: rgba(0, 0, 0, 0.5);
}
.ReactModal__Overlay--after-open {
  opacity: 1;
  transition: opacity 150ms ease-out;
}
.ReactModal__Content {
  -webkit-transform: scale(0.5) rotateX(-30deg);
}
.ReactModal__Content--after-open {
  -webkit-transform: scale(1) rotateX(0deg);
  transition: all 150ms ease-in;
}
.ReactModal__Overlay--before-close {
  opacity: 0;
}
.ReactModal__Content--before-close {
  -webkit-transform: scale(0.5) rotateX(30deg);
  transition: all 150ms ease-in;
}
.ReactModal__Content.modal-dialog {
  border: none;
  background-color: transparent;
}
```

you are supposed to modify the `.ReactModal__Content` and `.ReactModal__Content--after-open` to make the effect of entering for modal
